### ISSUE TITLE
Unrecognized resource pack format

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#1]
I have a few resource packs that give me an error when importing them.
The error is as follows:

> The file "filename" doesn't have any resourcepack format the launcher is aware of. Do you want to add it anyways?"

I'm just confused as these resource packs have worked completely fine for me in the past and inspecting the mcmeta files for each don't reveal and errors or typos. What could be the cause of this issue?
The packs I get the error for are: [Voidomon's Wolf Pack](https://www.curseforge.com/minecraft/texture-packs/voidomons-wolf-pack), [xali's Enhanced Vanilla](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla), and [xali's Potions](https://www.curseforge.com/minecraft/texture-packs/xalis-potions).
Notably, I also have another resource pack by xali and the issue is NOT present there.

1. Will these resource packs still work ingame if they've worked for me before?
2. Is this an issue of the packs themselves when freshly downloaded, or did I mess something up when editing the mcmeta files for the launcher not to recognize them?

**Comment by Tre5et** [comment]
Hey, thanks for reporting this.

Your packs will still work fine in game, they may just not be displayed properly in the launcher.

I will take a look at these packs soon and try to figure out, why this happens. It may likely be that I misunderstood some less commonly used part of the McMeta format.

**Comment by Tre5et** [comment]
This issue was fixed in the latest release, v2.2.3.
