### ISSUE TITLE
Error When Searching/Downloading Mods

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#13]
I keep getting this error when searching and downloading mods:
![image](https://github.com/user-attachments/assets/82141016-ec5c-40c7-9a34-59a832e6f821)
If the error shows up as a banner, it is easily dismissed. Occasionally it pops up as a dialog box which crashes the program.
The searching and downloading themselves work fine _eventually?_ But this is a very strange error that did not occur before. (Notably, lots of thumbnails for mods now aren't showing up.)
[2024-09-11_9.log.gz](https://github.com/user-attachments/files/16970731/2024-09-11_9.log.gz)

**Comment by viiuan** [comment]
It seems that this was only occuring in 2.5.0, as since I've updated to 2.5.2 it no longer happens.

**Comment by viiuan** [comment]
Nevermind, just happened in 2.5.2. It's actually really annoying since it keeps crashing the app.

**Comment by Tre5et** [comment]
This is a very strange issue, which I can not reproduce at the moment. I have a suspicion why this might happen, but I need to confirm this before I can do anything about it.
Could you send me your settings file found in `<data-directory>/.launcher/settings.json`? The data directory is `C:/Users/<name>/AppData/Local/treelauncher-data` by default.

**Comment by viiuan** [comment]
[settings.json](https://github.com/user-attachments/files/16981901/settings.json)
^^ this is from a fresh install where the issue persists
