### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by SweKalken** [Tre5et/treelauncher#16]
I'm unable to login to the launcher. After entering my email and such, the "Let this app access your info?" window is blank.

**Comment by Tre5et** [comment]
Hi, thanks for reporting this. Unfortunately, I can't reproduce this problem. I suggest trying to reinstall the launcher, making sure to delete the previous installation fully.

If the issue still persists, please send a screenshot of the window. Make sure it doesn't include any personal information though.

**Comment by SweKalken** [comment]
The issue remained after reinstalling multiple times! But by installing 2.5 first I was then able to log in as intended.

Now, on the other hand, when doing a clean uninstall using BCUninstaller and installing 2.5.2 again, everything works. Since this was a week ago or so, perhaps a simple restart of my pc solved the issue?
