### ISSUE TITLE
getting stuck on white blank screen after install and upgrade message

### ISSUE THREAD

**Issue by leevee123** [Tre5et/treelauncher#18]
![TreeLauncher_odbo68jcPY](https://github.com/user-attachments/assets/58a99916-f62f-45b2-925a-708c6b7ca78c)

**Comment by Tre5et** [comment]
Hey, thanks for reporting this. Could you provide some details here? From which version to which version are you upgrading? Can you attach a copy of the logs, found in your install directory (default: `C:/Users/[name]/AppData/local/TreeLauncher`) under `logs/current.log`?

**Comment by leevee123** [comment]
> Hey, thanks for reporting this. Could you provide some details here? From which version to which version are you upgrading? Can you attach a copy of the logs, found in your install directory (default: `C:/Users/[name]/AppData/local/TreeLauncher`) under `logs/current.log`?
[current.log](https://github.com/user-attachments/files/18004784/current.log)

i downloaded 3.0.1 and it doesnt say what version its upgrading to

**Comment by leevee123** [comment]
![TreeLauncher_1UFTbrmRxS](https://github.com/user-attachments/assets/83f8b6f6-c7cc-48bf-ad57-fd082f79d915)

**Comment by Tre5et** [comment]
This is fixed in v3.0.2. You should now no longer wrongly get this message after first install.

**Comment by leevee123** [comment]
after downloading new version it still asks to start upgrade and is blank, sam
[current.log](https://github.com/user-attachments/files/18011826/current.log)
e issue

**Comment by leevee123** [comment]
i deleted the data folder and the other one in local and it started to work again i think

**Comment by Tre5et** [comment]
Oh, yeah. I should have mentioned that trying to upgrade when it shouldn't have been possible to likely corrupted some metadata files. It is expected, that you'd have to delete the directory and redo the setup process.
