### ISSUE TITLE
UI issue when creating a new instance

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#2]
When selecting to create, copy, or use a mod component when creating an instance, the "use existing component" dropdown is only functional when selecting "copy existing component". If you select the option in the dropdown before you click "use existing component" it still lets you create the instance, but this seems like an oversight.
![image](https://github.com/Tre5et/treelauncher/assets/63260365/49243222-c1e8-4693-b853-60d4b21920ec)
![image](https://github.com/Tre5et/treelauncher/assets/63260365/f8b2bf74-c1d2-4eb4-a337-c28bd7e0f1e4)

**Comment by Tre5et** [comment]
Thanks for reporting this issue.

This is definitely an error and will be fixed in the next update, which should be ready in the next couple of days.

**Comment by Tre5et** [comment]
This issue was fixed in the latest release, v2.2.3.
