### ISSUE TITLE
[Suggestion] UI options

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#4]
I adore the simplicity and readability of this launcher's design so far, but I find myself occasionally missing things because of how big everything is, mostly when scrolling through the contents of a component.

It would be nice to be able to adjust the UI zoom (unless that's something I missed) and/or font size, or even toggle different views for the component contents list (e.g. default, compact, card, etc.).

Obviously this isn't a hugely urgent thing, but if you ever have the time and feel like it, I think it could be useful for accessibility purposes and varying user needs.

(Also, I think perhaps the mod disable/enable button could be improved in terms of intuitiveness. I almost opened an issue about adding that option in before double-checking since I didn't expect the toggle button to be a puzzle piece icon on the right side! I think it might be better to have checkboxes to the left of mods for toggling.)

**Comment by Tre5et** [comment]
I might implement something like font scaling at some point.
While I don't really have a problem seeing everything I need to see on my screen, I can definitely understand that this may make sense.
Especially the idea of having different list display modes seems pretty good though.

The enable button is also an accessibility concern that I am aware of, but haven't really found a good solution to. I don't really like using so many checkboxes, and would much rather use an icon like all the other action buttons. Maybe I need to find a more fitting icon and make it clearer at a glance that a mod is disabled. Possibly a little tutorial text when you add your first mod would also help.
Either way, I've got to try some things here.

**Comment by Tre5et** [comment]
List view options are now available for saves, resourcepacks and mods in v2.2.4.
If you like, I'd appreciate feedback on these.

I'm keeping this issue open because I plan to add more in this regard, this is just what I had basically ready with the hotfix for #5.

**Comment by viiuan** [comment]
I think these are great! Only thing is that I wish the icons were retained in the compact and minimal layouts, even if they're made smaller.

**Comment by Tre5et** [comment]
Version 2.3.0 adds an option for UI scaling and re-adds images to the compact list view (they end up being too small in the minimal view).
Improved visuals for enabling and disabling mods are also included.

Feel free to let me know if there is anything else you would like to see improved in this regard.

**Comment by viiuan** [comment]
hey, these additions are awesome :D thank you so much
