### ISSUE TITLE
UI: Importing too many items into an empty component hides the import button

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#6]
This happens when I drag-and-drop. Basically, having 11 or more items to import into a component at once hides the import button, and you have to delete items to reveal the button. (For clarity, this means that scrolling down to the button does not work.)
Edit: It only does this when you are adding items to the component for the first time/the component is empty.

**Comment by Tre5et** [comment]
Fixed in v2.2.4.
