### ISSUE TITLE
Cleaning Game Resources getting stuck

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#8]
Related to issue #5 but I figure since that was about the inconsistent files specifically I'd open this. Anyhow, this seems to be happening to all of my instances eventually and I'm not sure what triggers it or if it's just something that the launcher fuddles up sometimes.
It means that I have to force close the launcher for anything to happen and it always results in inconsistent files. Sometimes, the launcher can repair itself, but other times it's impossible and I have to fully reinstall.
I know this is a very weird issue since it's honestly impossible to reliably reproduce as far as I can see, but I can continue to send logs whenever it happens. Here's one from tonight where afterwards the launcher was able to repair itself.
(I don't know how to deliver these log.gz files in plaintext but I'm hoping you know how...)
[2024-05-04_2.log.gz](https://github.com/Tre5et/treelauncher/files/15211657/2024-05-04_2.log.gz)

**Comment by Tre5et** [comment]
Again, I appreciate sending in these logs and your patience, and I hope I will get this issue figured out soon. This is very strange and something that has never happened to me, using the launcher for multiple months almost daily now.

Please keep any further comments on this in #5 though, so it's easier for me to keep track of.
