### ISSUE TITLE
Update to 2.2.4 failed

### ISSUE THREAD

**Issue by viiuan** [Tre5et/treelauncher#9]
![image](https://github.com/Tre5et/treelauncher/assets/63260365/11d353c8-855e-4338-810c-a9595ec2520f)
[2024-05-06_1.log.gz](https://github.com/Tre5et/treelauncher/files/15222644/2024-05-06_1.log.gz)
[current.log](https://github.com/Tre5et/treelauncher/files/15222647/current.log)
Edit: Tried this twice and got the same error.

**Comment by Tre5et** [comment]
It's fixed for now and updating should work again.
